title: Aethelgard
description: "Ein browserbasiertes Fantasy-MMORPG – Wähle dein Schicksal. Forme deine Legende."
theme: jekyll-theme-midnight
lang: de

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: "de"
    values:
      layout: default
      lang: de
  - scope:
      path: "en"
    values:
      layout: default
      lang: en
